fix issue#132
oasisprotocol/oasis-web3-gateway pull request #134
Opened 2021-12-29 04:23 UTC by lesterli

Fix #132, please review and merge it, thanks.

2022-01-04 08:00 UTC, kostko reviewed
Please add some tests for the newly supported variants.

2022-01-04 08:00 UTC, kostko commented on rpc/eth/api.go
> +		round, err := api.backend.QueryBlockRound(*blockNrOrHash.BlockHash)
```suggestion
		return api.backend.QueryBlockRound(*blockNrOrHash.BlockHash)
```

2022-01-04 08:00 UTC, kostko commented on rpc/eth/api.go
> +		round, err := api.roundParamFromBlockNum(logger, *blockNrOrHash.BlockNumber)
```suggestion
		return api.roundParamFromBlockNum(logger, *blockNrOrHash.BlockNumber)
```

2022-01-06 08:56 UTC, ptrus requested changes
Can the following methods also be updated:
- `eth_getBalance`
- `eth_getStorageAt`
- `eth_getTransactionCount`
- `eth_getCode`

so that the full EIP-1898 is implemented (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md).

2022-02-08 15:58 UTC, ptrus commented
This was done in https://github.com/oasisprotocol/emerald-web3-gateway/pull/173

2022-02-08 15:58 UTC, closed without merging